### ISSUE TITLE
Sitemap indexes?

### ISSUE THREAD

**Issue by stevenvachon** [zrrrzzt/sitemap-to-array#1]
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>
      <loc>http://www.example.com/sitemap1.xml.gz</loc>
      <lastmod>2004-10-01T18:23:17+00:00</lastmod>
   </sitemap>
   <sitemap>
      <loc>http://www.example.com/sitemap2.xml.gz</loc>
      <lastmod>2005-01-01</lastmod>
   </sitemap>
</sitemapindex>
```

http://www.sitemaps.org/protocol.html#sitemapXMLExample

**Comment by zrrrzzt** [comment]
Hi @stevenvachon thank you for your interest in this module.

I made this to solve a particular problem at work and haven't given the possibilities of expansion much thought.

Your idea for supporting sitemap indexes is not bad at all. I'm no quite sure how I would design the result though. 

Personally I'm a big fan of very small modules so my instincts tells me this is best solved by a separate module. You would then use sitemapindexes-to-array and loop through the results and send each url to this module.

**Comment by stevenvachon** [comment]
I think that it should all be in one library, but it might end up smaller than it currently is. With a stream-or-xml-string input, we could remove `request` as a dependency. We could have two functions, one for dealing with map indexes and one for dealing with regular maps.

I also think that it isn't the job of this library to check that urls are valid -- it simply makes a sitemap usable.

**Comment by zrrrzzt** [comment]
Support for sitemapindexes is added. Works the same way as sitemaps. Input url or data to get an array.
