### ISSUE TITLE
stream-parse xml?

### ISSUE THREAD

**Issue by stevenvachon** [zrrrzzt/sitemap-to-array#2]
with [tagstream](https://www.npmjs.com/tagstream) or [xmlstream2](https://www.npmjs.com/xmlstream2)

The entire document string(s) would not need to be stored in memory, thereby greatly increasing performance.

**Comment by zrrrzzt** [comment]
I'll put this on my way to large todo-list :-)
If you have the time yourself just send me a pr @stevenvachon

**Comment by zrrrzzt** [comment]
I've decided not to do this. Size limit for a single sitemap is 10MB according to [www.sitemaps.org](http://www.sitemaps.org/faq.html#faq_sitemap_size).

**Comment by stevenvachon** [comment]
That's a 10MB string in memory that takes longer to do anything with and still needs to be garbage collected. If there's a sitemap index with multiple 10MB sitemap, the problem multiplies.

**Comment by zrrrzzt** [comment]
Did some tests https://gist.github.com/zrrrzzt/1df168f828ba996a32d1 and it was fun :-)

Maybe I'll do this anyway.
